import { NextResponse } from 'next/server'
import { requireAppContext, monthlyEquivalent, annualEquivalent, nextDate } from '@/lib/app-data'
const DEPTS=['Engineering','Marketing','Finance','Operations','HR','Sales']; const CATS=['Cloud','Software','Collaboration','Security','CRM','Storage','Productivity','Design']; const VENDORS=['AWS','Microsoft','Google','Slack','Zoom','Adobe','Canva','GitHub','Notion','Atlassian','HubSpot','Dropbox'];
const names=['AWS Cloud Infrastructure','Microsoft 365','Google Workspace','Slack Business','Zoom Business','Adobe Creative Cloud','Canva Pro','GitHub Enterprise','Notion Plus','Atlassian Cloud','HubSpot Pro','Dropbox Business'];
function dateBack(days:number){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
export async function POST(){try{const {supabase,organization}=await requireAppContext();const {count:existing}=await supabase.from('transactions').select('id',{count:'exact',head:true}).eq('organization_id',organization.id);if((existing||0)>0) return NextResponse.json({message:'Demo data already exists'})
let deptIds:any[]=[];for(const n of DEPTS){let {data}=await supabase.from('departments').select('id').eq('organization_id',organization.id).eq('name',n).maybeSingle();if(!data){const x=await supabase.from('departments').insert({organization_id:organization.id,name:n}).select('id').single();if(x.error)throw x.error;data=x.data}deptIds.push(data.id)}
const vendorIds:any[]=[];for(const n of VENDORS){let {data}=await supabase.from('vendors').select('id').eq('organization_id',organization.id).eq('normalized_name',n.toLowerCase()).maybeSingle();if(!data){const x=await supabase.from('vendors').insert({organization_id:organization.id,name:n,normalized_name:n.toLowerCase()}).select('id').single();if(x.error)throw x.error;data=x.data}vendorIds.push(data.id)}
const subs:any[]=[];for(let i=0;i<48;i++){const vi=i%VENDORS.length, di=i%deptIds.length, cost=450+(i%12)*275, f=i%4===0?'annual':i%3===0?'quarterly':'monthly', renewal=dateBack(-(10+(i*7)%330));subs.push({organization_id:organization.id,vendor_id:vendorIds[vi],department_id:deptIds[di],name:`${names[vi]} ${i>=12?'Team '+(i+1):''}`.trim(),description:`Business commitment for ${VENDORS[vi]}`,category:CATS[i%CATS.length],owner:DEPTS[di]+' Manager',cost,currency:'INR',billing_frequency:f,monthly_cost:monthlyEquivalent(cost,f),annual_cost:annualEquivalent(cost,f),start_date:dateBack(400+i*3),renewal_date:renewal,auto_renew:i%2===0,status:i%9===0?'under_review':'active',utilization:i%7===0?'low':i%3===0?'medium':'high',active_users: i%7===0?8:30+i%20,licensed_users:50+i%20,last_used_date:dateBack(i%30),notes:'Seeded demo record'})}
const ins=await supabase.from('subscriptions').insert(subs).select('id,renewal_date,cost,organization_id');if(ins.error)throw ins.error
const tx:any[]=[];for(let i=0;i<1000;i++){const vi=i%VENDORS.length,di=i%deptIds.length, recurring=i%5===0;const amount=recurring?700+(vi*310):150+(i%37)*83;tx.push({organization_id:organization.id,department_id:deptIds[di],vendor_id:vendorIds[vi],transaction_date:dateBack((i*3)%365),description:recurring?`${VENDORS[vi]} recurring charge`:`${VENDORS[vi]} business expense`,amount,currency:'INR',payment_method:i%3===0?'Card':'Bank Transfer',category:CATS[i%CATS.length]})}for(let i=0;i<tx.length;i+=200){const x=await supabase.from('transactions').insert(tx.slice(i,i+200));if(x.error)throw x.error}
const recurring:any[]=[];for(let i=0;i<80;i++){const vi=i%VENDORS.length,di=i%deptIds.length,f=i%4===0?'annual':i%3===0?'quarterly':'monthly',avg=650+(i%20)*170;const last=dateBack(i%30);recurring.push({organization_id:organization.id,vendor_id:vendorIds[vi],description:`${VENDORS[vi]} recurring commitment`,frequency:f,average_amount:avg,monthly_equivalent:monthlyEquivalent(avg,f),annual_equivalent:annualEquivalent(avg,f),confidence:78+(i%22),department_id:deptIds[di],category:CATS[i%CATS.length],last_payment_date:last,next_expected_date:nextDate(last,f),status:i%6===0?'under_review':'confirmed'})}let x=await supabase.from('recurring_expenses').insert(recurring);if(x.error)throw x.error
const renewals=(ins.data||[]).map((s:any)=>({organization_id:organization.id,subscription_id:s.id,renewal_date:s.renewal_date,amount:s.cost,review_status:'pending'}));for(let i=0;i<renewals.length;i+=100){x=await supabase.from('renewals').insert(renewals.slice(i,i+100));if(x.error)throw x.error}
for(const pair of [[0,1],[2,3],[4,5],[6,7],[8,9]]){const s1=ins.data?.[pair[0]],s2=ins.data?.[pair[1]];if(!s1||!s2)continue;const g=await supabase.from('duplicate_groups').insert({organization_id:organization.id,reason:'Similar vendor purpose and overlapping business workflow',combined_annual_cost:Number(s1.cost)+Number(s2.cost),status:'under_review'}).select('id').single();if(g.error)throw g.error;x=await supabase.from('duplicate_items').insert([{duplicate_group_id:g.data.id,subscription_id:s1.id},{duplicate_group_id:g.data.id,subscription_id:s2.id}]);if(x.error)throw x.error}
await supabase.from('notifications').insert([{organization_id:organization.id,type:'renewal',title:'Demo renewals loaded',message:'Review upcoming renewal commitments in the Renewals workspace.'},{organization_id:organization.id,type:'duplicate',title:'Potential duplicates found',message:'Five seeded review groups are ready for comparison.'}]);
return NextResponse.json({transactions:1000,subscriptions:48,recurring:80,renewals:renewals.length,duplicates:5})}catch(e:any){return NextResponse.json({error:e.message||'Seed failed'},{status:500})}}
